server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stats
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    ru.practicum.stats: DEBUG
    org.hibernate.SQL: DEBUG