server:
  port: ${SERVER_PORT:0}
  address: 0.0.0.0

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{application}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always