CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    text VARCHAR(2000) NOT NULL,

    author_id BIGINT NOT NULL,
    author_name VARCHAR(250) NOT NULL,

    event_id BIGINT NOT NULL,

    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated TIMESTAMP WITHOUT TIME ZONE,

    status VARCHAR(20) NOT NULL,

    moderator_id BIGINT,
    moderator_name VARCHAR(250),
    moderated_at TIMESTAMP WITHOUT TIME ZONE
    );

CREATE INDEX IF NOT EXISTS idx_comments_event_status
    ON comments (event_id, status);

CREATE INDEX IF NOT EXISTS idx_comments_author_id
    ON comments (author_id);

CREATE INDEX IF NOT EXISTS idx_comments_status
    ON comments (status);