server:
  port: ${SERVER_PORT:8091}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:aggregator-user-actions}
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer

      value-deserializer: ru.practicum.ewm.stats.serialization.UserActionAvroDeserializer

    listener:
      ack-mode: record
      concurrency: 1

    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer

      value-serializer: ru.practicum.ewm.stats.serialization.SpecificAvroSerializer

      acks: all
      retries: 10

      properties:
        enable.idempotence: true

kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    registry-fetch-interval-seconds: ${EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS:3}

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

    instance-id: ${spring.application.name}:${server.port}:${random.value}

    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always