CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    title VARCHAR(120) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    created_on TIMESTAMP NOT NULL,
    published_on TIMESTAMP,
    paid BOOLEAN NOT NULL,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT true,
    state VARCHAR(20) NOT NULL,
    initiator_id BIGINT NOT NULL,
    initiator_name VARCHAR(250) NOT NULL,
    category_id BIGINT NOT NULL
    REFERENCES categories(id)
    ON DELETE RESTRICT,
    lat FLOAT,
    lon FLOAT
);

CREATE INDEX IF NOT EXISTS idx_events_initiator_id
    ON events (initiator_id);

CREATE INDEX IF NOT EXISTS idx_events_category_id
    ON events (category_id);

CREATE INDEX IF NOT EXISTS idx_events_state_date
    ON events (state, event_date);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL
    REFERENCES compilations(id)
    ON DELETE CASCADE,

    event_id BIGINT NOT NULL
    REFERENCES events(id)
    ON DELETE CASCADE,

    PRIMARY KEY (compilation_id, event_id)
);