server:
  port: ${SERVER_PORT:0}
  address: 0.0.0.0
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/requests}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

      client:
        config:
          user-service:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: basic

          event-service:
            connectTimeout: 1000
            readTimeout: 2000
            loggerLevel: basic

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true

        ignore-exceptions:
          - "feign.FeignException$FeignClientException"

  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    registry-fetch-interval-seconds: ${EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS:3}

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS:3}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS:10}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.practicum.ewm.request: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG