server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0

spring:
  cloud:
    gateway:
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/events/**,/categories/**,/compilations/**,/users/**,/admin/**,/comments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 2
    initial-instance-info-replication-interval-seconds: 1
    instance-info-replication-interval-seconds: 5

    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always